# Generated by Django 2.2.6 on 2020-01-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('field', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
