# Generated by Django 2.2.6 on 2020-01-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0002_auto_20200115_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonote',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='geonote',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
