# Generated by Django 2.2.6 on 2020-01-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0003_auto_20200115_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonote',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
