# Generated by Django 2.2.6 on 2020-01-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0004_geonote_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('field', models.CharField(max_length=60)),
                ('index_name', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now=True)),
                ('filepath', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StackedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('field', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now=True)),
                ('filepath', models.URLField()),
            ],
        ),
    ]
