# Generated by Django 2.2.6 on 2020-01-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0015_auto_20200116_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=20)),
                ('fields', models.CharField(max_length=10000)),
            ],
        ),
    ]
