# Generated by Django 2.2.6 on 2020-01-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0016_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overlayimage',
            old_name='metadatafilepath',
            new_name='tiffilepath',
        ),
    ]
