# Generated by Django 2.2.6 on 2020-01-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0017_auto_20200119_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonote',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='geonote',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14),
        ),
    ]
