# Generated by Django 2.2.6 on 2020-01-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0018_auto_20200120_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
