# Generated by Django 2.2.6 on 2020-01-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0020_rawimageset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
    ]
