# Generated by Django 2.2.6 on 2020-01-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0021_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='long_name',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='index',
            name='summary',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
