# Generated by Django 2.2.6 on 2020-01-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_api', '0022_auto_20200123_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=60)),
                ('user', models.CharField(max_length=60)),
                ('latitude', models.DecimalField(decimal_places=10, default=0, max_digits=14)),
                ('longitude', models.DecimalField(decimal_places=10, default=0, max_digits=14)),
            ],
        ),
    ]
